### PR TITLE
Exclude transitive vulnerable dependency from telegrambots module

### PR DESCRIPTION
**Pull request by rob93c**
`telegrambots` module's dependency [**org.apache.httpcomponents.httpclient 4.5.13**](https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.13) provides transitive vulnerable dependency [**commons-codec.commons-codec 1.11**](https://mvnrepository.com/artifact/commons-codec/commons-codec/1.11).

On this regard, IntelliJ highlights the following:

- [Cxeb68d52e-5509](https://devhub.checkmarx.com/cve-details/Cxeb68d52e-5509/) 3.7 Exposure of Sensitive Information to an Unauthorized Actor

I checked if newer versions of `org.apache.httpcomponents.httpclient` upgraded that dependency but the [latest](https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.14) is still exporting `commons-codec.commons-codec 1.11`.

Sorting this out will also fix the same issue for the modules `telegrambots-abilities`, `telegrambots-chat-session-bot`, `telegrambots-extensions`, and `telegrambots-spring-boot-starter`:

image

### CODE REVIEW

**Comment by rob93c** [comment]
Hi @rubenlagus,
I had a deeper look into this and I found other transitive vulnerabilities:

- in `telegrambots-chat-session-bot`, `org.apache.shiro:shiro-core 1.10.0` provides transitive vulnerable dependency `commons-collections:commons-collections 3.2.2`
- in `telegrambots-spring-boot-starter`, `org.springframework.boot:spring-boot-starter-test 2.7.5` provides transitive vulnerable dependency `org.yaml:snakeyaml 1.30`

Let me know if you think they should be sorted out as part of this pull request.

**Comment by slavino** [comment]
so you suggest https://mvnrepository.com/artifact/org.apache.shiro/shiro-core in ver. 1.11.0 (released 13-Jan-2023) or 1.10.1 (released 18-Nov-2022) containing some level of CVE fixes.

**Comment by slavino** [comment]
https://mvnrepository.com/artifact/org.yaml/snakeyaml

keeps vulnerabilities along with all later releases and seems that this cannot be fixed now unless it is/was dropped from spring-boot-starter-test in ver. 2.7.6+ or 3.0.0+

**Comment by rob93c** [comment]
Hi @slavino, both of them would still provide transitive vulnerabilities even with their latest release.
I'd suggest, if that's a feasible solution, to exclude those 2 transitive dependencies from shiro-core and spring-boot-starter-test

**Comment by rubenlagus** [comment]
It was my mistake, this one was not the one I wanted to close, sorry

**Pull request closed without merging**
