### PR TITLE
Command bot additions

### PR DESCRIPTION
**Pull request by Mit0x2**
Cleaned up some JavaDoc, which I missed on my CommandBot contribution...

Added example for new Command capabilities to readme.md

Cheers

### CODE REVIEW

**Comment by rubenlagus** [comment]
Maybe it makes sense to add a simple example in the samples project? Maybe a bot that just support:
- /start -> Welcome message
- /hello -> Send a "Hello world!" message
- Any other command -> Send a "Default command received" 
- Any other thing -> Send a "Not command found" 


What do you think? Won't that cover all cases easily?

**Comment by Mit0x2** [comment]
Hi,
could do sth like that as well. I thought like this it would be all together. So people would't have to look into another project.
Just close this pull request if you like an example bot in your Example project better. I'll then reopen a pull request with the attached minor javadoc changes.

**Comment by rubenlagus** [comment]
Yep, if you like the idea, we can close this one until we have the example one and then add a nice reference from https://github.com/rubenlagus/TelegramBots#example-bots toguether with the other fixes you added in the docs (something that indeed needs a lot of work.. I wish I had time to write documentation...)

**Comment by Mit0x2** [comment]
> something that indeed needs a lot of work.. I wish I had time to write documentation...
Will help out there in the near future. Probably will hijack the telegram group for questions :P

Will make the example later and add a pull request like mentioned.

**Pull request closed without merging**
