### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Anas-ind**
some changes

### CODE REVIEW

**Review by addo37 — COMMENTED** [review]
Seriously? At least make it lowercase.

**Review by Anas-ind — COMMENTED** [review]
just a small change

**Comment by kortov** [comment]
I guess it's for #shitoberfest

**Comment by Anas-ind** [comment]
Yeah a  kind of and I'll looking more to contribute in open source just a
beginning
Thank

**Comment by rubenlagus** [comment]
Please, do a pull request against dev branch, not master

**Pull request closed without merging**
