### PR TITLE
CommandRegistry: Replace botUsername with botUsernameSupplier

### LINKED ISSUE #796: TelegramLongPollingCommandBot can't get correct botUserName
[TelegramLongPollingCommandBot](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-extensions/src/main/java/org/telegram/telegrambots/extensions/bots/commandbot/TelegramLongPollingCommandBot.java)

In constructor `public TelegramLongPollingCommandBot(DefaultBotOptions options, boolean allowCommandsWithUsername)`
method `getBotUsername()` returns null if the name is pulled through the class field, from a config-file for example

### PR DESCRIPTION
**Pull request by alexengrig**
Fix #796 and #770.

### CODE REVIEW

**Comment by rubenlagus** [comment]
@alexengrig Can we keep the original constructor but mark it as deprecated? Otherwise it will be a breaking change:

`public CommandRegistry(boolean allowCommandsWithUsername, String botUsername) `

**Comment by alexengrig** [comment]
@rubenlagus Return the original constructor. Need to mark it as deprecated?

**Comment by rubenlagus** [comment]
@alexengrig if the old constructor fix issue #770 no need, otherwise, let mark is as deprecated

**Comment by rubenlagus** [comment]
@alexengrig In that case, better to deprecate it and add something to the docs to state that situation. I'll make sure it is removed in next major version

**Comment by alexengrig** [comment]
@rubenlagus Done.

**Pull request merged**
