### PR TITLE
Fix SendPhoto jsonProperties

### PR DESCRIPTION
**Pull request by BlackDragoon**
This fix resolve the Bad request error during a SendPhoto call

### CODE REVIEW

**Comment by rubenlagus** [comment]
SendPhoto doesn't use a Json format when called, it has a custom execute method defined in DefaultAbsSender. Why are you getting the error? Can you share the example code that raise it?

**Comment by BlackDragoon** [comment]
Hi Ruben,
I'm using the SendPhoto builder to create the HttpEntity body in a doExchange of restTemplate http call. 
The SendMessage class has the jsonProperty annotations, it could be good insert it into the SendPhoto class as it, what do you think?
Thanks a lot
--
Inviato da Libero Mail per Android Sabato, 01 Gennaio 2022, 11:37PM +01:00 da Ruben Bermudez  ***@***.*** :

**Comment by rubenlagus** [comment]
@BlackDragoon how do you plan to serialize the InputFile object?

**Comment by timursergeevichname** [comment]
@BlackDragoon Hi. The documentation says

> This object represents the contents of a file to be uploaded. Must be posted using multipart/form-data in the usual way that files are uploaded via the browser. [inputfile](https://core.telegram.org/bots/api#inputfile)

SendMessage use method
 ```java
// AbsSender.java 
public <T extends Serializable, Method extends BotApiMethod<T>> T execute(Method method) throws TelegramApiException {
        if (method == null) {
            throw new TelegramApiException("Parameter method can not be null");
        }
        return sendApiMethod(method);
    }
```
```java 
// DefaultAbsSender 
   @Override
    protected final <T extends Serializable, Method extends BotApiMethod<T>> T sendApiMethod(Method method) throws TelegramApiException {
        try {
            String responseContent = sendMethodRequest(method);
            return method.deserializeResponse(responseContent);
        } catch (IOException e) {
            throw new TelegramApiException("Unable to execute " + method.getMethod() + " method", e);
        }
    }
```


methods that require files to be uploaded use the special execute methods. e.g. sendPhoto use
```java
public final Message execute(SendPhoto sendPhoto) throws TelegramApiException {
        assertParamNotNull(sendPhoto, "sendPhoto");

        sendPhoto.validate();
        try {
            String url = getBaseUrl() + SendPhoto.PATH;
            HttpPost httppost = configuredHttpPost(url);

            MultipartEntityBuilder builder = MultipartEntityBuilder.create();
            builder.setLaxMode();
            builder.setCharset(StandardCharsets.UTF_8);
            builder.addTextBody(SendPhoto.CHATID_FIELD, sendPhoto.getChatId(), TEXT_PLAIN_CONTENT_TYPE);
            addInputFile(builder, sendPhoto.getPhoto(), SendPhoto.PHOTO_FIELD, true);
```

**Pull request closed without merging**
