### PR TITLE
Create TimedSendLongPollingBot.java

### PR DESCRIPTION
**Pull request by JetCoder1**
LongPollingBot extension performing time-based sends complying basic Telegram limits (no more 30 messages per second in different chats, no more 1 message per second in any single chat).

### CODE REVIEW

**Comment by Davide95** [comment]
As said in the chat, it'll we very useful if merged in the library. Good work ^^

**Comment by rubenlagus** [comment]
Hi @Davide95, I'm going to create a separate project for this extension, the Command one (will be taken out from base api) and some other that will come. 

They will be delivered with separate Maven artifacts so each dev can get what he need. I'll let you know the exact URL of the project.

**Comment by Davide95** [comment]
@rubenlagus  why not just merge into that project? :dagger:

**Comment by rubenlagus** [comment]
I can merge, but it will end up in the other project as well. I can move it later, as you liike

**Comment by rubenlagus** [comment]
I merged it, I'll take it to the other project as soon as it is ready.

**Comment by Davide95** [comment]
Hi, when TimedSendLongPollingBot will be released on the stable branch and can be used through maven? I've the 3.1.2 version but I don't find any TimedSendLongPollingBot

**Comment by rubenlagus** [comment]
@Davide95 It has been released since v3.0.2: https://github.com/rubenlagus/TelegramBots/blob/v3.0.2/telegrambots-extensions/src/main/java/org/telegram/telegrambots/bots/timedbot/TimedSendLongPollingBot.java

**Comment by Davide95** [comment]
I'm using v3.2 through maven
```
<dependency>
            <groupId>org.telegram</groupId>
            <artifactId>telegrambots</artifactId>
            <version>3.2</version>
</dependency>
```

I'm able to use classes inside org.telegram.telegrambots.bots but there isn't any org.telegram.telegrambots.bots.timedbot. What's wrong? Maybe I'm missing something

**Pull request merged**
