### PR TITLE
Added Bukkit support

### PR DESCRIPTION
**Pull request by Azim-D3Tm**
Added Bukkit support:
Now bukkit plugins can use TelegramBotsAPI !

### CODE REVIEW

**Comment by Clevero** [comment]
The [README](https://github.com/rubenlagus/TelegramBots#contributions) states:

```Feel free to fork this project, work on it and then make a pull request against DEV branch.```

This PR is against master

**Comment by Azim-D3Tm** [comment]
Sorry, i'll re-push it to dev

**Comment by Clevero** [comment]
thanks :D

**Comment by Azim-D3Tm** [comment]
i'm still new at github, how do i delete this one?

**Comment by Clevero** [comment]
Just close this pull request^^

**Pull request closed without merging**
