### PR TITLE
Change Ability name check according to Telegram bot API requirements

### PR DESCRIPTION
**Pull request by Daniil547**
Currently Ability `name`  is checked to contain alpha-numeric characters and no white spaces (beside not being null nor empty).
This doesn't correspond with Telegram API requirements, which are:

> "A command must always start with the '/' symbol and may not be longer than 32 characters. Commands can use latin letters, numbers and underscores." (https://core.telegram.org/bots#commands)

This PR makes underscores allowed to use in Ability `name` and adds check for its length (requirement of leading '/' is irrelevant because Ability `name` isn't a command itself, just a "name" of a command, so to speak; however this '/' has to be taken into account, since it leaves 31 character for the rest of the command)

### CODE REVIEW

**Review by addo37 — APPROVED** [review]
Thanks for making these changes, @Daniil547.

**Comment by zundarik** [comment]
Good afternoon. This change is badly needed. An underscore is required in the command name.
We need to make changes to the line checkArgument (isAlphanumeric (name), "Method name can only be alpha-numeric", name);
It does not accept the underscore.

**Comment by Chase22** [comment]
It's funny how "can use underscores" became "must use underscores" in just 3 comments

**Comment by rubenlagus** [comment]
@zundarik Do the pull request against dev branch

**Comment by Daniil547** [comment]
> 
> @rubenlagus:
> @zundarik Do the pull request against dev branch

I was the one who opened the PR, so I suppose that should have been addressed to me. I'll do that.

**Pull request merged**
