### PR TITLE
Modify DefaultAbsSender.java for issue #494

### PR DESCRIPTION
**Pull request by genjiezio**
#494 
I try to use the ThreadPool (**newCachedThreadPool**) to excute the sendphoto Async.
And it has a good performance , which can be seen in this url:
https://github.com/genjiezio/ImageRepository/blob/main/BSY8UISCOQD752OGHMO91MF.png

### CODE REVIEW

**Comment by genjiezio** [comment]
So, after I pull a request for this method, the Coverage told that  a **excuteAsync** had been created in this .java file, which use **CompletableFuture**,  which i didn't notice.
So why not close the issue #494 ?
Does this means it still  need to be improve?

**Comment by rubenlagus** [comment]
Please do the request against dev branch.

And would help having a simple Unit Test for the new method 😅

**Comment by genjiezio** [comment]
> Please do the request against dev branch.
> 
> And would help having a simple Unit Test for the new method 😅

Yeah, i'd like to do that. But actually, now I find you had wrote a **excuteAsync** in the 2020 which i didn't notice when i wrote this method, does this means the issue was solved by you in 2020?  Then why still keep this issue?

For the Unit Test, actually, i think it difficult to test use Junit. I test the method by manually send signals concurrently to the bot but it's still can't judge whether it really excute asynchronously because the excute time is only about 40ms. 

No matter how, i'll try to write a Unit test as much as possiable. I do this request because I can't get yours advice from the issue page since i commented in the issue page **#494** in March, so i want to get your attention in this pr, I really want to help in this issue.

>

**Comment by rubenlagus** [comment]
Correct, the problem was fixed with the addition of the async methods, so no need to add any other methods here

`public CompletableFuture<Message> executeAsync(SendPhoto sendPhoto)`

**Pull request closed without merging**
