### PR TITLE
Separate AbilityBot logic and implement Webhook, closes #422

### LINKED ISSUE #422: Provide AbilityBot, working with WebHook
AbilityBot API is absolutely awesome. It's much less boilerplate and makes it easier to concentrate on the logic of application instead of spaghetti-filtering.
But it's impossible to scale LongPolling-based bots and scaling is essential when you're building HA applications.

### PR DESCRIPTION
**Pull request by addo37**

### CODE REVIEW

**Comment by addo37** [comment]
@rubenlagus Take in the new AbilityBot. The chunk of code has been moved to BaseAbilityBot and AbilityBot simply extends it and implement long polling. Thanks!

**Comment by rubenlagus** [comment]
@addo37 This pull requests have conflicts. Also, can you confirm it is completely backward compatible with current version?

**Comment by addo37** [comment]
Yes, every person extending AbilityBot will still be using the default LongPolling method. User code won't change.

In essence, it's backward compatible.

**Comment by addo37** [comment]
@rubenlagus done

**Comment by addo37** [comment]
@rubenlagus Some changes will require your review.

The initial implementation of this PR had the ability bot instantiate the webhook/longpolling Telegram bot in its constructor. The main purpose was to use the code in clearWebhook and setWebhook for the ability bot. When called, it would delegate the calls to the underlying bot.

Since that's unnecessary and I didn't want to add duplicate code, I've refactored those two functions into their own util class. However, this ushered in the change of DefaultAbsSender#getBaseUrl to be public. I've inspected the code and it didn't seem to be a huge issue to make the method public, but it certainly needs your opinion. I've cleaned up some code as well meanwhile in TelegramWebhookBot (Options were being set when it was not needed at all. It was simply a duplicate reference).

If you approve the change, I'm fine with the merge. If not, let me know and I'll amend accordingly.

**Pull request merged**
